ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "displayTitleOverride" TEXT;
ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "coverUrlOverride" TEXT;
ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "animeTypeOverride" TEXT;
ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "tagsOverride" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "overrideNote" TEXT;
ALTER TABLE "PoolAnime" ADD COLUMN IF NOT EXISTS "overrideUpdatedAt" TIMESTAMP(3);
