"use client";

import Link from "next/link";
import React, { useState } from "react";
import { AnimeCover } from "./AnimeCover";
import { AppBadge } from "./ui/AppBadge";
import { AppButton, appButtonClasses } from "./ui/AppButton";
import { getAnimeDisplayTitle, shouldUseContainCover } from "@/lib/anime-display";
import type { PublicTierShare, TierShareSnapshotItem } from "@/lib/client-api";
import { copyToClipboard } from "@/lib/clipboard";
import { formatDateTimeStable } from "@/lib/date-format";

export function TierShareView({ share }: { share: PublicTierShare }) {
  const [copied, setCopied] = useState(false);
  const [copyFallback, setCopyFallback] = useState(false);

  async function copyLink() {
    const href = window.location.href;
    const result = await copyToClipboard(href);
    if (result.ok) {
      setCopied(true);
      setCopyFallback(false);
    } else {
      setCopied(false);
      setCopyFallback(true);
    }
  }

  return (
    <main className="min-h-screen bg-[#101310] px-4 py-6 text-white sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <header className="mb-8 flex flex-col gap-4 rounded-3xl border border-cyan-300/20 bg-slate-950/70 p-5 shadow-[0_28px_100px_rgba(0,0,0,0.35)] sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex flex-wrap gap-2">
              <AppBadge tone="source">AniMatch</AppBadge>
              <AppBadge tone="tier">Tier Wall</AppBadge>
            </div>
            <h1 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">
              {share.title}
            </h1>
            <p className="mt-3 text-sm text-slate-400">
              生成于 {formatDateTimeStable(share.snapshot.generatedAt)}
            </p>
            {share.description ? (
              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">
                {share.description}
              </p>
            ) : null}
          </div>
          <div className="flex flex-wrap gap-3">
            <AppButton onClick={copyLink} variant="primary">
              {copied ? "链接已复制" : "复制链接"}
            </AppButton>
            <Link href="/" className={appButtonClasses({ variant: "ghost" })}>
              返回 AniMatch 首页
            </Link>
          </div>
          {copyFallback ? (
            <div className="mt-3 max-w-lg">
              <p className="text-xs text-red-300">自动复制失败，请手动复制下面的链接。</p>
              <input
                type="text"
                readOnly
                value={typeof window !== "undefined" ? window.location.href : ""}
                className="anime-field mt-2 w-full text-xs"
                onFocus={(e) => {
                  e.target.select();
                }}
              />
            </div>
          ) : null}
        </header>

        <section className="overflow-hidden rounded-2xl border border-black/80 bg-[#191d21] shadow-[0_20px_90px_rgba(0,0,0,0.35)]">
          {share.snapshot.tiers.map((tier) => (
            <div
              key={tier.key}
              className="grid min-h-28 grid-cols-[92px_1fr] border-b border-black/80 last:border-b-0 sm:grid-cols-[132px_1fr]"
            >
              <div className={`share-tier-label share-tier-label-${tier.key.toLowerCase()}`}>
                <span className="max-w-full text-center text-2xl font-extrabold leading-tight text-slate-950 [overflow-wrap:anywhere] sm:text-4xl">
                  {tier.label}
                </span>
              </div>
              <div className="flex min-h-28 flex-wrap content-start gap-3 bg-[#171b20] p-3">
                {tier.items.length === 0 ? (
                  <div className="flex h-24 items-center text-sm text-slate-500">
                    暂无作品
                  </div>
                ) : (
                  tier.items.map((item) => <ShareItemCard key={item.animeId} item={item} />)
                )}
              </div>
            </div>
          ))}
        </section>

        <p className="mt-5 text-right text-xs font-semibold uppercase tracking-[0.24em] text-slate-500">
          generated by animatch
        </p>
      </div>
    </main>
  );
}

export function TierShareMissingView() {
  return (
    <main className="flex min-h-screen items-center justify-center bg-[#101310] px-4 text-white">
      <div className="max-w-lg rounded-3xl border border-white/10 bg-slate-950/72 p-8 text-center shadow-[0_28px_100px_rgba(0,0,0,0.35)]">
        <AppBadge tone="tier">AniMatch</AppBadge>
        <h1 className="mt-5 text-3xl font-black">这个分享榜单不存在或已被删除。</h1>
        <p className="mt-3 text-sm leading-6 text-slate-400">
          请检查链接是否完整，或返回首页重新打开 AniMatch。
        </p>
        <Link href="/" className={`${appButtonClasses({ variant: "primary" })} mt-6`}>
          返回 AniMatch 首页
        </Link>
      </div>
    </main>
  );
}

function ShareItemCard({ item }: { item: TierShareSnapshotItem }) {
  const title = getAnimeDisplayTitle(item);
  const coverFit = shouldUseContainCover(item) ? "contain" : "cover";

  return (
    <article className="w-28 rounded-xl border border-white/10 bg-slate-950/72 p-2 shadow-[0_12px_36px_rgba(0,0,0,0.25)] sm:w-32">
      <AnimeCover
        src={item.coverUrl ?? null}
        title={title}
        size="sm"
        fit={coverFit}
        className="h-28 w-full rounded-lg sm:h-32"
      />
      <h2 className="mt-2 line-clamp-2 text-xs font-semibold leading-snug text-white">
        {title}
      </h2>
      <div className="mt-2 flex flex-wrap gap-1">
        <AppBadge tone="source">{item.source}</AppBadge>
        {item.animeType ? <AppBadge tone="status">{item.animeType}</AppBadge> : null}
      </div>
    </article>
  );
}
