"use client";

import Link from "next/link";
import React, { useState } from "react";
import { AnimeCover } from "./AnimeCover";
import { AppBadge } from "./ui/AppBadge";
import { AppButton, appButtonClasses } from "./ui/AppButton";
import { getAnimeCoverUrl } from "@/lib/anime-cover-url";
import {
  getAnimeDisplayTitle,
  shouldUseContainCover
} from "@/lib/anime-display";
import type { PublicTierShare, TierShareSnapshotItem } from "@/lib/client-api";
import { copyToClipboard } from "@/lib/clipboard";
import { formatDateTimeStable } from "@/lib/date-format";
import { proxyExternalImageUrl } from "@/lib/image-proxy";

export function TierShareView({
  share,
  exportMode = false
}: {
  share: PublicTierShare;
  exportMode?: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [copyFallback, setCopyFallback] = useState(false);
  const creatorLabel = getShareCreatorLabel(share);
  const creatorUsername = getShareCreatorUsername(share);

  async function copyLink() {
    const href = window.location.href;
    const result = await copyToClipboard(href);
    if (result.ok) {
      setCopied(true);
      setCopyFallback(false);
    } else {
      setCopied(false);
      setCopyFallback(true);
    }
  }

  return (
    <main className="min-h-screen bg-[#101310] px-4 py-6 text-white sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        {!exportMode ? (
          <header className="mb-8 flex flex-col gap-4 rounded-3xl border border-cyan-300/20 bg-slate-950/70 p-5 shadow-[0_28px_100px_rgba(0,0,0,0.35)] sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="flex flex-wrap gap-2">
                <AppBadge tone="source">AniMatch</AppBadge>
                <AppBadge tone="tier">Tier List</AppBadge>
              </div>
              <h1 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">
                {share.title}
              </h1>
              <p className="mt-3 text-sm text-slate-400">
                生成于 {formatDateTimeStable(share.snapshot.generatedAt)}
              </p>
              {creatorLabel ? (
                <p className="mt-2 text-sm font-semibold text-cyan-100">
                  由{" "}
                  {creatorUsername ? (
                    <Link href={`/u/${creatorUsername}`} className="underline decoration-cyan-400/40 hover:text-cyan-200">
                      {creatorLabel}
                    </Link>
                  ) : (
                    creatorLabel
                  )}{" "}
                  制作这套 Tier List
                </p>
              ) : null}
              {share.description ? (
                <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">
                  {share.description}
                </p>
              ) : null}
            </div>
            <div className="flex flex-wrap gap-3">
              <AppButton onClick={copyLink} variant="primary">
                {copied ? "链接已复制" : "复制链接"}
              </AppButton>
              <Link href="/" className={appButtonClasses({ variant: "ghost" })}>
                返回 AniMatch 首页
              </Link>
            </div>
            {copyFallback ? (
              <div className="mt-3 max-w-lg">
                <p className="text-xs text-red-300">自动复制失败，请手动复制下面的链接。</p>
                <input
                  type="text"
                  readOnly
                  value={typeof window !== "undefined" ? window.location.href : ""}
                  className="anime-field mt-2 w-full text-xs"
                  onFocus={(e) => {
                    e.target.select();
                  }}
                />
              </div>
            ) : null}
          </header>
        ) : null}

        <TierShareCard share={share} exportMode={exportMode} />

        {!exportMode ? (
          <p className="mt-5 text-center text-xs text-slate-500">
            <span className="font-semibold uppercase tracking-[0.2em]">generated by AniMatch</span>
            <span className="mx-3 text-slate-600">·</span>
            <span>anime.animatch.app</span>
          </p>
        ) : null}
      </div>
    </main>
  );
}

export function TierShareCard({
  share,
  exportMode = false
}: {
  share: PublicTierShare;
  exportMode?: boolean;
}) {
  const creatorLabel = getShareCreatorLabel(share);
  const creatorUsername = getShareCreatorUsername(share);
  const animeCount = share.snapshot.animeCount ?? share.snapshot.tiers.reduce((sum, t) => sum + t.items.length, 0);
  const comparisonCount = share.snapshot.comparisonCount ?? null;
  const exportFooterText =
    share.snapshot.run.id === "community"
      ? "普通对决共享榜 · 匿名聚合社区结果"
      : share.snapshot.run.id.startsWith("season-shared")
        ? "赛季共享 TierList · 匿名聚合结果"
        : share.snapshot.run.id.startsWith("season-personal")
          ? "大乱斗赛季个人 Elo 结果"
          : "用左右对决生成个人 Tier List";

  return (
    <section
      data-tier-share-card={exportMode ? "true" : undefined}
      className="overflow-hidden rounded-2xl border border-black/80 bg-[#191d21] shadow-[0_20px_90px_rgba(0,0,0,0.35)]"
    >
      {exportMode ? (
        <header className="border-b border-cyan-300/15 bg-gradient-to-b from-[#0f1923] to-[#11161c] px-5 py-5 sm:px-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan-200/70">
                AniMatch Tier List
              </p>
              <h1 className="mt-2 text-2xl font-black leading-tight text-white sm:text-3xl">
                {share.title}
              </h1>
              {share.snapshot.isInitialEstimate ? (
                <p className="mt-2 inline-flex rounded-full border border-amber-200/30 bg-amber-200/10 px-2.5 py-1 text-xs font-semibold text-amber-100">
                  初始预览 · 尚未完成对决
                </p>
              ) : null}
              {creatorLabel ? (
                <p className="mt-1.5 text-sm font-semibold text-slate-300">
                  由{" "}
                  {creatorUsername ? (
                    <Link href={`/u/${creatorUsername}`} className="underline decoration-slate-500/40 hover:text-white">
                      {creatorLabel}
                    </Link>
                  ) : (
                    creatorLabel
                  )}{" "}
                  制作
                </p>
              ) : null}
            </div>
            <div className="flex flex-wrap gap-3 text-xs text-slate-400">
              <span>{animeCount} 作品</span>
              {comparisonCount !== null ? <span>{comparisonCount} 对决</span> : null}
            </div>
          </div>
        </header>
      ) : null}
      {share.snapshot.tiers.map((tier) => {
        const tierColor = tier.color ?? "#ff747c";
        return (
        <div
          key={tier.key}
          className="grid min-h-24 grid-cols-[82px_1fr] border-b border-black/80 last:border-b-0 sm:grid-cols-[120px_1fr]"
        >
          <div
            className="share-tier-label flex items-center justify-center px-1"
            style={{ backgroundColor: tierColor }}
          >
            <span className="max-w-full text-center text-xl font-extrabold leading-tight text-slate-950 [overflow-wrap:anywhere] sm:text-3xl">
              {tier.label}
            </span>
          </div>
          <div className="flex min-h-24 flex-wrap content-start gap-2 bg-[#171b20] p-2">
            {tier.items.length === 0 ? (
              <div className="flex h-24 items-center text-sm text-slate-500">
                暂无作品
              </div>
            ) : (
              tier.items.map((item) => (
                <ShareItemCard key={item.animeId} item={item} exportMode={exportMode} />
              ))
            )}
          </div>
        </div>
        );
      })}
      {exportMode ? (
        <footer className="border-t border-cyan-300/10 bg-[#0f1722] px-5 py-4">
          <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-cyan-200/50">
              generated by AniMatch
            </p>
              <p className="text-[11px] text-slate-500">
                anime.animatch.app · {exportFooterText}
              </p>
            </div>
          </footer>
      ) : null}
    </section>
  );
}

export function TierShareMissingView() {
  return (
    <main className="flex min-h-screen items-center justify-center bg-[#101310] px-4 text-white">
      <div className="max-w-lg rounded-3xl border border-white/10 bg-slate-950/72 p-8 text-center shadow-[0_28px_100px_rgba(0,0,0,0.35)]">
        <AppBadge tone="tier">AniMatch</AppBadge>
        <h1 className="mt-5 text-3xl font-black">这个分享榜单不存在或已被删除。</h1>
        <p className="mt-3 text-sm leading-6 text-slate-400">
          请检查链接是否完整，或返回首页重新打开 AniMatch。
        </p>
        <Link href="/" className={`${appButtonClasses({ variant: "primary" })} mt-6`}>
          返回 AniMatch 首页
        </Link>
      </div>
    </main>
  );
}

function ShareItemCard({
  item,
  exportMode = false
}: {
  item: TierShareSnapshotItem;
  exportMode?: boolean;
}) {
  const title = getAnimeDisplayTitle(item);
  const coverFit = shouldUseContainCover(item) ? "contain" : "cover";
  const rawCoverUrl = getAnimeCoverUrl(item, { intent: "export" });
  const coverUrl = exportMode ? proxyExternalImageUrl(rawCoverUrl) : rawCoverUrl;

  return (
    <article className="w-28 rounded-xl border border-white/10 bg-slate-950/72 p-2 shadow-[0_12px_36px_rgba(0,0,0,0.25)] sm:w-32">
      <AnimeCover
        src={coverUrl}
        secondarySrc={exportMode ? rawCoverUrl : undefined}
        title={title}
        size="sm"
        fit={coverFit}
        className="h-28 w-full rounded-lg sm:h-32"
      />
      {!exportMode ? (
        <h2 className="mt-2 line-clamp-2 text-[10px] font-semibold leading-snug text-slate-400">
          {title}
        </h2>
      ) : (
        <h2 className="sr-only">{title}</h2>
      )}
    </article>
  );
}

function getShareCreatorLabel(share: PublicTierShare): string | null {
  const value = share.snapshot.creator?.displayName?.trim();
  return value && value.length > 0 ? value : null;
}

function getShareCreatorUsername(share: PublicTierShare): string | null {
  const value = share.snapshot.creator?.username?.trim();
  return value && value.length > 0 ? value : null;
}
