mixed-port: 7890
external-controller: '127.0.0.1:9090'
allow-lan: false
bind-address: "127.0.0.1"
mode: rule
log-level: info

geox-url:
  geoip: "/etc/mihomo/geoip.dat"
  geosite: "/etc/mihomo/geosite.dat"
  mmdb: "/etc/mihomo/geoip.metadb"

proxy-providers:
  sub:
    type: http
    url: "https://b.592851.xyz/api/v1/client/subscribe?token=78bd71852e67d966f08043ca0e57d9f8"
    path: ./providers/sub.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: AUTO
    type: url-test
    use:
      - sub
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50

  - name: PROXY
    type: select
    proxies:
      - AUTO
      - DIRECT
    use:
      - sub

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
    - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN

rules:
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
