ALTER TABLE "Anime" ALTER COLUMN "bgmId" DROP NOT NULL;

ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "titleJa" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "titleEn" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "aliases" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "year" INTEGER;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "season" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "animeType" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "episodes" INTEGER;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "studios" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "externalLinks" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'BANGUMI';
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "sourceId" TEXT;

UPDATE "Anime"
SET
  "aliases" = COALESCE("aliases", ARRAY[]::TEXT[]),
  "studios" = COALESCE("studios", ARRAY[]::TEXT[]),
  "externalLinks" = COALESCE("externalLinks", ARRAY[]::TEXT[]),
  "source" = COALESCE(NULLIF("source", ''), 'BANGUMI');

UPDATE "Anime"
SET "sourceId" = "bgmId"::TEXT
WHERE "bgmId" IS NOT NULL AND ("sourceId" IS NULL OR "sourceId" = '');

ALTER TABLE "Anime" ALTER COLUMN "source" SET DEFAULT 'BANGUMI';
ALTER TABLE "Anime" ALTER COLUMN "source" SET NOT NULL;
ALTER TABLE "Anime" ALTER COLUMN "aliases" SET DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Anime" ALTER COLUMN "studios" SET DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Anime" ALTER COLUMN "externalLinks" SET DEFAULT ARRAY[]::TEXT[];

CREATE UNIQUE INDEX IF NOT EXISTS "Anime_bgmId_key" ON "Anime"("bgmId");
