ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverUrl" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverKey" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverWidth" INTEGER;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverHeight" INTEGER;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverFormat" TEXT;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverBytes" INTEGER;
ALTER TABLE "Anime" ADD COLUMN IF NOT EXISTS "cachedCoverAt" TIMESTAMP(3);
